### PR TITLE
Add MDS stats

### PR DESCRIPTION
**Pull request by RDruon**
Fix EX-7930

```
# HELP lustre_mds_mdt_fld_stats MDS mdt_fld stats
# TYPE lustre_mds_mdt_fld_stats gauge
lustre_mds_mdt_fld_stats{operation="req_waittime",units="usec"} 39 0
lustre_mds_mdt_fld_stats{operation="req_qdepth",units="reqs"} 39 0
lustre_mds_mdt_fld_stats{operation="req_active",units="reqs"} 39 0
lustre_mds_mdt_fld_stats{operation="req_timeout",units="sec"} 39 0
lustre_mds_mdt_fld_stats{operation="reqbuf_avail",units="bufs"} 88 0
lustre_mds_mdt_fld_stats{operation="fld_query",units="usec"} 35 0
lustre_mds_mdt_fld_stats{operation="fld_read",units="usec"} 4 0

# HELP lustre_mds_mdt_out_stats MDS mdt_out stats
# TYPE lustre_mds_mdt_out_stats gauge
lustre_mds_mdt_out_stats{operation="req_waittime",units="usec"} 40673 0
lustre_mds_mdt_out_stats{operation="req_qdepth",units="reqs"} 40673 0
lustre_mds_mdt_out_stats{operation="req_active",units="reqs"} 40673 0
lustre_mds_mdt_out_stats{operation="req_timeout",units="sec"} 40673 0
lustre_mds_mdt_out_stats{operation="reqbuf_avail",units="bufs"} 83413 0
lustre_mds_mdt_out_stats{operation="ldlm_ibits_enqueue",units="reqs"} 1 0
lustre_mds_mdt_out_stats{operation="mds_statfs",units="usec"} 40642 0
lustre_mds_mdt_out_stats{operation="obd_ping",units="usec"} 1 0
lustre_mds_mdt_out_stats{operation="out_update",units="usec"} 29 0

# HELP lustre_mds_mdt_readpage_stats MDS mdt_readpage stats
# TYPE lustre_mds_mdt_readpage_stats gauge
lustre_mds_mdt_readpage_stats{operation="req_waittime",units="usec"} 7640 0
lustre_mds_mdt_readpage_stats{operation="req_qdepth",units="reqs"} 7640 0
lustre_mds_mdt_readpage_stats{operation="req_active",units="reqs"} 7640 0
lustre_mds_mdt_readpage_stats{operation="req_timeout",units="sec"} 7640 0
lustre_mds_mdt_readpage_stats{operation="reqbuf_avail",units="bufs"} 15656 0
lustre_mds_mdt_readpage_stats{operation="mds_getattr",units="usec"} 3 0
lustre_mds_mdt_readpage_stats{operation="mds_close",units="usec"} 7632 0
lustre_mds_mdt_readpage_stats{operation="mds_readpage",units="usec"} 5 0

# HELP lustre_mds_mdt_seqm_stats MDS mdt_seqm stats
# TYPE lustre_mds_mdt_seqm_stats gauge
lustre_mds_mdt_seqm_stats{operation="req_waittime",units="usec"} 5 0
lustre_mds_mdt_seqm_stats{operation="req_qdepth",units="reqs"} 5 0
lustre_mds_mdt_seqm_stats{operation="req_active",units="reqs"} 5 0
lustre_mds_mdt_seqm_stats{operation="req_timeout",units="sec"} 5 0
lustre_mds_mdt_seqm_stats{operation="reqbuf_avail",units="bufs"} 14 0
lustre_mds_mdt_seqm_stats{operation="seq_query",units="usec"} 5 0

# HELP lustre_mds_mdt_seqs_stats MDS mdt_seqs stats
# TYPE lustre_mds_mdt_seqs_stats gauge
lustre_mds_mdt_seqs_stats{operation="req_waittime",units="usec"} 8 0
lustre_mds_mdt_seqs_stats{operation="req_qdepth",units="reqs"} 8 0
lustre_mds_mdt_seqs_stats{operation="req_active",units="reqs"} 8 0
lustre_mds_mdt_seqs_stats{operation="req_timeout",units="sec"} 8 0
lustre_mds_mdt_seqs_stats{operation="reqbuf_avail",units="bufs"} 18 0
lustre_mds_mdt_seqs_stats{operation="seq_query",units="usec"} 8 0

# HELP lustre_mds_mdt_stats MDS mdt stats
# TYPE lustre_mds_mdt_stats gauge
lustre_mds_mdt_stats{operation="req_waittime",units="usec"} 110689 0
lustre_mds_mdt_stats{operation="req_qdepth",units="reqs"} 110689 0
lustre_mds_mdt_stats{operation="req_active",units="reqs"} 110689 0
lustre_mds_mdt_stats{operation="req_timeout",units="sec"} 110689 0
lustre_mds_mdt_stats{operation="reqbuf_avail",units="bufs"} 250496 0
lustre_mds_mdt_stats{operation="ldlm_ibits_enqueue",units="reqs"} 21296 0
lustre_mds_mdt_stats{operation="mds_reint_setattr",units="reqs"} 228 0
lustre_mds_mdt_stats{operation="mds_reint_create",units="reqs"} 9 0
lustre_mds_mdt_stats{operation="mds_reint_unlink",units="reqs"} 7 0
lustre_mds_mdt_stats{operation="mds_reint_open",units="reqs"} 7641 0
lustre_mds_mdt_stats{operation="ost_set_info",units="usec"} 130 0
lustre_mds_mdt_stats{operation="mds_connect",units="usec"} 38 0
lustre_mds_mdt_stats{operation="mds_disconnect",units="usec"} 2 0
lustre_mds_mdt_stats{operation="mds_get_root",units="usec"} 3 0
lustre_mds_mdt_stats{operation="mds_statfs",units="usec"} 15 0
lustre_mds_mdt_stats{operation="mds_sync",units="usec"} 224 0
lustre_mds_mdt_stats{operation="obd_ping",units="usec"} 88737 0
```

### CODE REVIEW

**Comment by jgrund** [comment]
@RDruon @breuhan Does this still need to be in draft?

**Comment by RDruon** [comment]
Looking

**Comment by jgrund** [comment]
Needs more coverage

**Comment by RDruon** [comment]
> Needs more coverage

The missing coverage is coming from the fixture. I am looking to get some stats on the following stats:

- `lctl get_param mds.MDS.mdt_setattr.stats`
- `lctl get_param mds.MDS.mdt_out.stats` 

I tried to use DoM without success (`lfs setstripe -E 1M -L mdt -E EOF /lustre/fs/client/test`)

**Comment by RDruon** [comment]
@jgrund please review

**Pull request merged**
